<?php

namespace App\Http\Controllers;

use App\Models\AiChatAssistant;
use App\Models\ChatbotWidget;
use Illuminate\Contracts\View\View;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\RedirectResponse;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Str;

/**
 * Workspace-scoped chatbot widgets. Each widget renders as a floating
 * bubble on the operator's website via a one-line embed snippet; the
 * actual chat UI loads from `/widget/{embed_token}/chat` and posts
 * messages back to `/widget/{embed_token}/api/message`. AI replies are
 * generated by an attached `AiChatAssistant`.
 */
class ChatbotWidgetController extends Controller
{
    public function index(): View
    {
        $wsId = (int) (Auth::user()?->current_workspace_id ?? 0);

        $widgets = ChatbotWidget::query()
            ->where('workspace_id', $wsId)
            ->withCount('visitors')
            ->orderByDesc('id')
            ->paginate(20)
            ->withQueryString();

        $stats = [
            'all'      => ChatbotWidget::where('workspace_id', $wsId)->count(),
            'active'   => ChatbotWidget::where('workspace_id', $wsId)->where('status', 'active')->count(),
            'visitors' => \App\Models\ChatbotWidgetVisitor::where('workspace_id', $wsId)->count(),
        ];
        return view('user.chatbot-widgets.index', compact('widgets', 'stats'));
    }

    public function create(): View
    {
        $wsId = (int) (Auth::user()?->current_workspace_id ?? 0);
        $assistants = AiChatAssistant::where('workspace_id', $wsId)
            ->where('status', 'active')->orderBy('name')->get(['id', 'name']);
        return view('user.chatbot-widgets.builder', [
            'widget'     => null,
            'mode'       => 'create',
            'assistants' => $assistants,
        ]);
    }

    public function edit(int $id): View
    {
        $wsId = (int) (Auth::user()?->current_workspace_id ?? 0);
        $widget = ChatbotWidget::where('workspace_id', $wsId)->findOrFail($id);
        $assistants = AiChatAssistant::where('workspace_id', $wsId)
            ->where('status', 'active')->orderBy('name')->get(['id', 'name']);
        return view('user.chatbot-widgets.builder', [
            'widget'     => $widget,
            'mode'       => 'edit',
            'assistants' => $assistants,
        ]);
    }

    public function apiSave(Request $request): JsonResponse
    {
        $user = Auth::user();
        $wsId = (int) ($user?->current_workspace_id ?? 0);
        if (!$wsId) return response()->json(['ok' => false, 'error' => 'no_workspace'], 400);

        $data = $request->validate([
            'id'                       => 'nullable|integer',
            'name'                     => 'required|string|max:120',
            'mode'                     => 'required|in:ai,whatsapp,both',
            'assistant_id'             => 'nullable|integer',
            'target_whatsapp_cc'       => 'nullable|string|max:8',
            'target_whatsapp_number'   => 'nullable|string|max:24',
            'prefilled_message'        => 'nullable|string|max:2000',
            'position'                 => 'required|in:bottom_right,bottom_left',
            'button_color'             => 'required|string|max:16',
            'button_image_url'         => 'nullable|string|max:1024',
            'header_title'             => 'required|string|max:120',
            'header_bg'                => 'required|string|max:16',
            'header_text_color'        => 'required|string|max:16',
            'welcome_message'          => 'nullable|string|max:2000',
            'message_bubble_color'     => 'required|string|max:16',
            'message_text_color'       => 'required|string|max:16',
            'body_bg_kind'             => 'required|in:color,image',
            'body_bg_color'            => 'required|string|max:16',
            'body_bg_image_url'        => 'nullable|string|max:1024',
            'auto_open'                => 'nullable|boolean',
            'button_label'             => 'required|string|max:80',
            'action_button_bg'         => 'required|string|max:16',
            'action_button_text_color' => 'required|string|max:16',
            'collect_name'             => 'nullable|boolean',
            'collect_email'            => 'nullable|boolean',
            'collect_phone'            => 'nullable|boolean',
            // CORS allow-list — empty array means "any origin", per
            // ChatbotWidget::originAllowed(). Each entry is a bare
            // host[:port]; the model normalises scheme + path on read.
            'allowed_domains'          => 'nullable|array|max:50',
            'allowed_domains.*'        => 'string|max:253',
        ]);

        // Normalise allowed_domains: strip scheme/path, lowercase, dedupe,
        // drop blanks. Done before fill() so the model's array cast
        // persists clean data and originAllowed() doesn't re-do it on
        // every public request.
        if (isset($data['allowed_domains'])) {
            $clean = [];
            foreach ($data['allowed_domains'] as $d) {
                $d = trim(strtolower((string) $d));
                if ($d === '') continue;
                $d = preg_replace('#^https?://#', '', $d);
                $d = rtrim(strtok($d, '/'), '/');
                if ($d !== '') $clean[$d] = true;
            }
            $data['allowed_domains'] = array_keys($clean);
        }

        // If mode requires AI, the assistant_id must resolve to a
        // workspace-scoped active assistant. Otherwise the visitor's
        // first message would hit the fallback path every time.
        if (in_array($data['mode'], ['ai', 'both'], true)) {
            if (empty($data['assistant_id'])) {
                return response()->json([
                    'ok' => false, 'error' => 'AI mode needs an assistant. Pick one or create one in AI Training.',
                ], 422);
            }
            $ok = AiChatAssistant::where('workspace_id', $wsId)
                ->where('id', $data['assistant_id'])->exists();
            if (!$ok) {
                return response()->json(['ok' => false, 'error' => 'Assistant not in this workspace.'], 422);
            }
        }

        $widget = !empty($data['id'])
            ? ChatbotWidget::where('workspace_id', $wsId)->find($data['id'])
            : null;

        if (!$widget) {
            $widget = new ChatbotWidget();
            $widget->workspace_id = $wsId;
            $widget->user_id      = $user->id;
            $widget->embed_token  = ChatbotWidget::freshToken();
        }

        // Unique slug per workspace.
        $base = Str::slug($data['name']) ?: ('widget-' . Str::random(6));
        $slug = $widget->slug ?: $base;
        $i = 1;
        while (ChatbotWidget::where('workspace_id', $wsId)
            ->where('slug', $slug)
            ->where('id', '!=', $widget->id ?? 0)
            ->exists()) {
            $slug = $base . '-' . (++$i);
        }
        $widget->slug = $slug;

        $widget->fill($data);
        $widget->save();

        return response()->json([
            'ok'           => true,
            'id'           => $widget->id,
            'embed_token'  => $widget->embed_token,
            'embed_url'    => url('/widget/' . $widget->embed_token . '/embed.js'),
            'preview_url'  => url('/widget/' . $widget->embed_token . '/chat'),
        ]);
    }

    public function duplicate(int $id): RedirectResponse
    {
        $wsId = (int) (Auth::user()?->current_workspace_id ?? 0);
        $src = ChatbotWidget::where('workspace_id', $wsId)->findOrFail($id);
        $copy = $src->replicate(['embed_token']);
        $copy->name        = $src->name . ' (copy)';
        $copy->slug        = $src->slug . '-copy-' . Str::random(4);
        $copy->embed_token = ChatbotWidget::freshToken();
        $copy->save();
        return redirect()->route('user.chatbot-widgets.edit', $copy->id);
    }

    public function destroy(int $id): JsonResponse
    {
        $wsId = (int) (Auth::user()?->current_workspace_id ?? 0);
        $widget = ChatbotWidget::where('workspace_id', $wsId)->findOrFail($id);
        $widget->delete();
        return response()->json(['ok' => true]);
    }

    /**
     * Rotate the embed_token. Use case: snippet leaked or pasted on
     * the wrong domain. After rotation the old snippet stops working.
     */
    public function rotateToken(int $id): JsonResponse
    {
        $wsId = (int) (Auth::user()?->current_workspace_id ?? 0);
        $widget = ChatbotWidget::where('workspace_id', $wsId)->findOrFail($id);
        $widget->embed_token = ChatbotWidget::freshToken();
        $widget->save();
        return response()->json([
            'ok'          => true,
            'embed_token' => $widget->embed_token,
            'embed_url'   => url('/widget/' . $widget->embed_token . '/embed.js'),
        ]);
    }
}
