<x-layouts.admin :title="__('Admin · Invoices')" admin-key="invoices" page="invoices-index">
    <header class="h-16 bg-paper-0 hairline-b border-b border-paper-200 flex items-center px-4 sm:px-6 lg:px-7 gap-4 sticky top-0 z-30">
        <div class="flex items-center gap-2 text-[12px] font-mono text-ink-500 shrink-0">
            <a href="{{ url('/admin') }}" class="uppercase tracking-[0.16em] hover:text-ink-900">{{ __('Admin') }}</a>
            <svg viewBox="0 0 12 12" class="w-2.5 h-2.5" fill="none" stroke="currentColor" stroke-width="1.6">
                <path d="M4 3l3 3-3 3" />
            </svg>
            <span class="text-ink-900 normal-case tracking-normal">{{ __('Invoices') }}</span>
        </div>
        <div class="ml-auto flex items-center gap-2" data-admin-header-right></div>
    </header>

    <main class="px-4 sm:px-6 lg:px-7 py-7 space-y-5">

        <div class="flex flex-col lg:flex-row lg:items-end justify-between gap-4">
            <div>
                <div class="font-mono text-[10px] uppercase tracking-[0.18em] text-ink-500 mb-2">
                    {{ __('Admin · Billing & plans · Invoices') }}</div>
                <h1 class="font-serif font-normal tracking-[-0.01em] text-[40px] leading-[1.0]">{{ __('All') }}
                    <span class="italic text-wa-deep">{{ __('invoices') }}</span></h1>
                <p class="text-[13px] text-ink-600 mt-2 max-w-2xl">
                    {{ __('PDF invoices generated by :app. Filter by status, regenerate, void, or send a copy to the workspace owner.', ['app' => brand_name()]) }}
                </p>
            </div>
            <div class="flex items-center gap-2 shrink-0 pb-1">
                <button
                    class="px-4 py-2 hairline border border-paper-200 rounded-full bg-paper-0 hover:bg-paper-50 text-[12px] font-medium flex items-center gap-2">
                    <svg viewBox="0 0 16 16" class="w-3.5 h-3.5" fill="none" stroke="currentColor"
                        stroke-width="1.6">
                        <path d="M8 2v8M5 7l3 3 3-3M3 12v2h10v-2" />
                    </svg>
                    {{ __('Export CSV') }}
                </button>
                <button
                    class="px-4 py-2 rounded-full bg-wa-deep text-paper-0 text-[12px] font-semibold hover:bg-wa-teal flex items-center gap-2">
                    <svg viewBox="0 0 16 16" class="w-3.5 h-3.5" fill="none" stroke="currentColor" stroke-width="2">
                        <path d="M8 3v10M3 8h10" />
                    </svg>
                    {{ __('Manual invoice') }}
                </button>
            </div>
        </div>

        <!-- KPI strip -->
        <section class="grid grid-cols-2 sm:grid-cols-3 lg:grid-cols-5 gap-3">
            <div class="bg-paper-0 border border-paper-200 rounded-2xl p-4 shadow-card">
                <div class="text-[11px] text-ink-600 font-medium">{{ __('Total invoices') }}</div>
                <div class="font-serif text-[34px] leading-none mt-1">{{ $stats['total'] }}</div>
                <div class="text-[11px] text-ink-500 mt-2">{{ __('all time') }}</div>
            </div>
            <div class="bg-paper-0 border border-wa-green/40 rounded-2xl p-4 shadow-card">
                <div class="text-[11px] text-ink-600 font-medium">{{ __('Paid') }}</div>
                <div class="font-serif text-[34px] leading-none mt-1">{{ $stats['paid'] }}</div>
                <div class="text-[11px] text-wa-deep mt-2">{{ $stats['paidPct'] }}</div>
            </div>
            <div class="bg-paper-0 border border-accent-amber/40 rounded-2xl p-4 shadow-card">
                <div class="text-[11px] text-ink-600 font-medium">{{ __('Outstanding') }}</div>
                <div class="font-serif text-[34px] leading-none mt-1">{{ $stats['outstanding'] }}</div>
                <div class="text-[11px] text-ink-500 mt-2">{{ $stats['outstandingAmt'] }}</div>
            </div>
            <div class="bg-paper-0 border border-accent-coral/40 rounded-2xl p-4 shadow-card">
                <div class="text-[11px] text-ink-600 font-medium">{{ __('Overdue') }}</div>
                <div class="font-serif text-[34px] leading-none mt-1 text-accent-coral">{{ $stats['overdue'] }}</div>
                <div class="text-[11px] text-accent-coral mt-2">{{ __('>15 days late') }}</div>
            </div>
            <div class="bg-paper-0 border border-paper-200 rounded-2xl p-4 shadow-card">
                <div class="text-[11px] text-ink-600 font-medium">{{ __('This month') }}</div>
                <div class="font-serif text-[34px] leading-none mt-1">{{ $stats['monthSum'] }}</div>
                <div class="text-[11px] {{ $stats['monthDeltaPos'] ? 'text-wa-deep' : 'text-accent-coral' }} mt-2">
                    {{ $stats['monthDelta'] }}</div>
            </div>
        </section>

        <!-- Filter row -->
        <form method="get" action="{{ url()->current() }}"
            class="bg-paper-0 border border-paper-200 rounded-2xl p-2 flex items-center gap-1 shadow-card flex-wrap">
            @php $statusPills = ['all' => 'All', 'paid' => 'Paid', 'outstanding' => 'Outstanding', 'overdue' => 'Overdue', 'refunded' => 'Refunded', 'void' => 'Void']; @endphp
            @foreach ($statusPills as $k => $label)
                <button type="submit" name="status" value="{{ $k }}"
                    class="filter-pill inline-flex items-center gap-1.5 px-4 py-[7px] rounded-full text-[13px] text-ink-600 cursor-pointer transition hover:bg-paper-50 [&.active]:bg-ink-900 [&.active]:text-paper-0 {{ $statusF === $k ? 'active' : '' }}">
                    {{ $label }}
                    @if ($k === 'all')
                        <span class="font-mono text-[11px] opacity-80">({{ $stats['total'] }})</span>
                    @elseif ($k === 'outstanding')
                        <span class="font-mono text-[11px] text-accent-amber">{{ $stats['outstanding'] }}</span>
                    @elseif ($k === 'overdue')
                        <span class="font-mono text-[11px] text-accent-coral">{{ $stats['overdue'] }}</span>
                    @endif
                </button>
            @endforeach
            <div class="flex-1"></div>
            <div class="flex items-center gap-1.5">
                <select name="window" onchange="this.form.submit()"
                    class="hairline border border-paper-200 rounded-full px-3 py-1.5 text-[12px] bg-paper-0 hover:bg-paper-50 focus:outline-none focus:border-wa-deep">
                    <option value="this_month" @selected($window === 'this_month')>{{ __('This month') }}</option>
                    <option value="last_month" @selected($window === 'last_month')>{{ __('Last month') }}</option>
                    <option value="this_quarter" @selected($window === 'this_quarter')>{{ __('This quarter') }}</option>
                    <option value="this_year" @selected($window === 'this_year')>{{ __('This year') }}</option>
                </select>
                <div class="relative">
                    <svg viewBox="0 0 16 16" class="w-3.5 h-3.5 absolute left-3 top-1/2 -translate-y-1/2 text-ink-500"
                        fill="none" stroke="currentColor" stroke-width="1.5">
                        <circle cx="7" cy="7" r="5" />
                        <path d="m11 11 3 3" />
                    </svg>
                    <input name="q" value="{{ $q }}"
                        placeholder="{{ __('Search by invoice #, workspace, owner…') }}"
                        class="hairline border border-paper-200 rounded-full pl-9 pr-3 py-1.5 text-[12px] bg-paper-0 w-72 focus:outline-none focus:border-wa-deep" />
                </div>
            </div>
        </form>

        <!-- Invoices table -->
        <div class="bg-paper-0 border border-paper-200 rounded-2xl shadow-card">
            <div class="overflow-x-auto">
            <table class="w-full text-[12.5px] table-fixed min-w-[1080px]">
                <thead class="bg-paper-50 text-ink-500 border-b border-paper-200">
                    <tr>
                        <th class="text-left px-3 py-2.5 w-[34px]"><input type="checkbox"
                                class="rounded border-paper-300"></th>
                        <th class="text-left px-3 py-2.5 w-[140px]">{{ __('Invoice #') }}</th>
                        <th class="text-left px-3 py-2.5 w-[110px]">{{ __('Issue date') }}</th>
                        <th class="text-left px-3 py-2.5 w-[110px]">{{ __('Due date') }}</th>
                        <th class="text-left px-3 py-2.5">{{ __('Workspace') }}</th>
                        <th class="text-left px-3 py-2.5">{{ __('Item') }}</th>
                        <th class="text-right px-3 py-2.5 w-[100px]">{{ __('Amount') }}</th>
                        <th class="text-center px-3 py-2.5 w-[100px]">{{ __('Status') }}</th>
                        <th class="text-center px-3 py-2.5 w-[80px]">{{ __('PDF') }}</th>
                        <th class="text-center px-3 py-2.5 w-[44px]"></th>
                    </tr>
                </thead>
                <tbody class="divide-y divide-paper-200">
                    @forelse ($invoices as $inv)
                        @php
                            $badge = \App\Http\Controllers\Admin\InvoicesController::badge($inv);
                            $package = $inv->package_id ? \App\Models\Package::find($inv->package_id) : null;
                            $rowBg =
                                $badge['label'] === 'outstanding'
                                    ? 'bg-accent-amber/5'
                                    : ($badge['label'] === 'overdue'
                                        ? 'bg-accent-coral/5'
                                        : '');
                            $dueDate = $inv->created_at;
                            $isOverdue = $badge['label'] === 'overdue';
                            $daysLate = $isOverdue ? $inv->created_at->diffInDays(now()) : null;
                            $amountTone = match ($inv->status) {
                                'paid' => 'text-wa-deep',
                                'refunded' => 'text-accent-coral',
                                'pending' => $isOverdue ? 'text-accent-coral' : '',
                                default => '',
                            };
                            $invoiceNumber = 'INV-' . str_replace('ORD_', '', strtoupper((string) $inv->order_number));
                        @endphp
                        <tr class="hover:bg-paper-50/60 {{ $rowBg }}">
                            <td class="px-3 py-3"><input type="checkbox" class="rounded border-paper-300"></td>
                            <td class="px-3 py-3 font-mono text-[11px]">{{ $invoiceNumber }}</td>
                            <td class="px-3 py-3 font-mono text-[11px]">{{ $inv->created_at->format('Y-m-d') }}</td>
                            <td class="px-3 py-3 font-mono text-[11px] {{ $isOverdue ? 'text-accent-coral' : '' }}">
                                {{ $dueDate->format('Y-m-d') }}{{ $isOverdue ? ' · ' . $daysLate . 'd late' : '' }}
                            </td>
                            <td class="px-3 py-3">
                                <div class="font-semibold leading-tight">
                                    {{ $inv->workspace?->name ?? 'Workspace #' . $inv->workspace_id }}</div>
                                <div class="text-[10.5px] text-ink-500 font-mono">
                                    {{ $inv->customer_email ?? ($inv->customer_name ?? '—') }}</div>
                            </td>
                            <td class="px-3 py-3">
                                <div class="text-[12px]">{{ $package?->pname ?? 'Add-on' }} @if ($package)
                                        · {{ $package->plan_unit }}
                                    @endif
                                </div>
                                <div class="text-[10.5px] text-ink-500">
                                    {{ $inv->status === 'refunded' ? 'refunded' : $inv->created_at->format('Y-m-d') . ' → ' . $inv->created_at->copy()->addMonth()->format('Y-m-d') }}
                                </div>
                            </td>
                            <td class="px-3 py-3 text-right font-mono {{ $amountTone }}">
                                {{ $inv->status === 'refunded' ? '-' : '' }}{!! \App\Support\FormatSettings::formatIn((float) ($inv->total_amount ?? $inv->amount), $inv->currency) !!}</td>
                            <td class="px-3 py-3 text-center"><span
                                    class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full {{ $badge['class'] }} text-[10.5px] font-mono"><span
                                        class="w-1.5 h-1.5 rounded-full {{ $badge['dot'] }}"></span>{{ $badge['label'] }}</span>
                            </td>
                            <td class="px-3 py-3 text-center"><a href="{{ route('admin.invoices.view', $inv->id) }}"
                                    class="inline-flex w-7 h-7 rounded-full border border-paper-200 hover:border-wa-deep hover:bg-wa-bubble text-wa-deep grid place-items-center"
                                    title="{{ __('View invoice') }}"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5"
                                        fill="none" stroke="currentColor" stroke-width="1.6">
                                        <path d="M8 2v8m0 0L5 7m3 3 3-3M3 13h10" />
                                    </svg></a></td>
                            <td class="px-3 py-3 text-center">
                                <div class="relative inline-block" data-row-menu><button type="button"
                                        class="w-8 h-8 rounded-full hover:bg-paper-50 grid place-items-center mx-auto"
                                        data-row-menu-toggle><svg viewBox="0 0 16 16" class="w-3.5 h-3.5 text-ink-600"
                                            fill="currentColor">
                                            <circle cx="3" cy="8" r="1.2" />
                                            <circle cx="8" cy="8" r="1.2" />
                                            <circle cx="13" cy="8" r="1.2" />
                                        </svg></button>
                                    <div data-row-menu-panel
                                        class="hidden absolute right-0 top-full mt-1 z-50 w-[180px] bg-paper-0 border border-paper-200 rounded-xl shadow-soft py-1 text-left">
                                        <a href="{{ route('admin.invoices.view', $inv->id) }}"
                                            class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('View') }}</a>
                                        @if ($inv->workspace_id)
                                            <a href="{{ route('admin.workspaces.detail', $inv->workspace_id) }}"
                                                class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Open workspace') }}</a>
                                        @endif
                                    </div>
                                </div>
                            </td>
                        </tr>
                    @empty
                        <tr>
                            <td colspan="10" class="px-4 py-10 text-center text-ink-500">
                                {{ __('No invoices in this window.') }}</td>
                        </tr>
                    @endforelse
                    @if (false)
                        <tr>
                            <div
                                class="inv-action-menu hidden absolute right-0 top-full mt-1 z-50 w-[180px] bg-paper-0 border border-paper-200 rounded-xl shadow-soft py-1 text-left">
                                <a href="{{ url('/admin/invoices/1') }}"
                                    class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('View') }}</a>
                                <button
                                    class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Email to owner') }}</button>
                                <button
                                    class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Regenerate PDF') }}</button>
                                <div class="border-t border-paper-200 my-1"></div>
                                <button
                                    class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-accent-amber hover:bg-accent-amber/10">{{ __('Issue refund') }}</button>
                                <button
                                    class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-accent-coral hover:bg-accent-coral/10">{{ __('Void') }}</button>
                            </div>
        </div>
        </td>
        </tr>

        <tr class="hover:bg-paper-50/60">
            <td class="px-3 py-3"><input type="checkbox" class="rounded border-paper-300"></td>
            <td class="px-3 py-3 font-mono text-[11px]">{{ __('INV-2026-04820') }}</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-04-11</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-04-11</td>
            <td class="px-3 py-3">
                <div class="font-semibold leading-tight">{{ __('FitKart') }}</div>
                <div class="text-[10.5px] text-ink-500 font-mono">{{ __('Meera S.') }}</div>
            </td>
            <td class="px-3 py-3">
                <div class="text-[12px]">{{ __('Pro · monthly') }}</div>
                <div class="text-[10.5px] text-ink-500">2026-04-11 → 2026-05-11</div>
            </td>
            <td class="px-3 py-3 text-right font-mono text-wa-deep">$1,499.00</td>
            <td class="px-3 py-3 text-center"><span
                    class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-wa-mint text-wa-deep text-[10.5px] font-mono"><span
                        class="w-1.5 h-1.5 rounded-full bg-wa-green"></span>paid</span></td>
            <td class="px-3 py-3 text-center"><a href="{{ url('/admin/invoices/1') }}"
                    class="inline-flex w-7 h-7 rounded-full border border-paper-200 hover:border-wa-deep hover:bg-wa-bubble text-wa-deep grid place-items-center"
                    title="{{ __('View invoice') }}"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5" fill="none"
                        stroke="currentColor" stroke-width="1.6">
                        <path d="M8 2v8m0 0L5 7m3 3 3-3M3 13h10" />
                    </svg></a></td>
            <td class="px-3 py-3 text-center">
                <div class="relative inline-block"><button type="button"
                        class="w-8 h-8 rounded-full hover:bg-paper-50 grid place-items-center mx-auto"
                        onclick="toggleInvMenu(event,this)"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5 text-ink-600"
                            fill="currentColor">
                            <circle cx="3" cy="8" r="1.2" />
                            <circle cx="8" cy="8" r="1.2" />
                            <circle cx="13" cy="8" r="1.2" />
                        </svg></button>
                    <div
                        class="inv-action-menu hidden absolute right-0 top-full mt-1 z-50 w-[180px] bg-paper-0 border border-paper-200 rounded-xl shadow-soft py-1 text-left">
                        <a href="{{ url('/admin/invoices/1') }}"
                            class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('View') }}</a>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Email to owner') }}</button>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Regenerate PDF') }}</button>
                        <div class="border-t border-paper-200 my-1"></div>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-accent-amber hover:bg-accent-amber/10">{{ __('Issue refund') }}</button>
                    </div>
                </div>
            </td>
        </tr>

        <tr class="hover:bg-paper-50/60 bg-accent-amber/5">
            <td class="px-3 py-3"><input type="checkbox" class="rounded border-paper-300"></td>
            <td class="px-3 py-3 font-mono text-[11px]">{{ __('INV-2026-04816') }}</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-04-08</td>
            <td class="px-3 py-3 font-mono text-[11px] text-accent-amber">2026-04-08</td>
            <td class="px-3 py-3">
                <div class="font-semibold leading-tight">{{ __('QuickBite') }}</div>
                <div class="text-[10.5px] text-ink-500 font-mono">{{ __('Ravi T.') }}</div>
            </td>
            <td class="px-3 py-3">
                <div class="text-[12px]">{{ __('Starter · monthly') }}</div>
                <div class="text-[10.5px] text-ink-500">2026-04-08 → 2026-05-08</div>
            </td>
            <td class="px-3 py-3 text-right font-mono">$129.00</td>
            <td class="px-3 py-3 text-center"><span
                    class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-accent-amber/10 text-accent-amber text-[10.5px] font-mono"><span
                        class="w-1.5 h-1.5 rounded-full bg-accent-amber"></span>outstanding</span></td>
            <td class="px-3 py-3 text-center"><a href="{{ url('/admin/invoices/1') }}"
                    class="inline-flex w-7 h-7 rounded-full border border-paper-200 hover:border-wa-deep hover:bg-wa-bubble text-wa-deep grid place-items-center"
                    title="{{ __('View invoice') }}"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5" fill="none"
                        stroke="currentColor" stroke-width="1.6">
                        <path d="M8 2v8m0 0L5 7m3 3 3-3M3 13h10" />
                    </svg></a></td>
            <td class="px-3 py-3 text-center">
                <div class="relative inline-block"><button type="button"
                        class="w-8 h-8 rounded-full hover:bg-paper-50 grid place-items-center mx-auto"
                        onclick="toggleInvMenu(event,this)"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5 text-ink-600"
                            fill="currentColor">
                            <circle cx="3" cy="8" r="1.2" />
                            <circle cx="8" cy="8" r="1.2" />
                            <circle cx="13" cy="8" r="1.2" />
                        </svg></button>
                    <div
                        class="inv-action-menu hidden absolute right-0 top-full mt-1 z-50 w-[180px] bg-paper-0 border border-paper-200 rounded-xl shadow-soft py-1 text-left">
                        <a href="{{ url('/admin/invoices/1') }}"
                            class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('View') }}</a>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-wa-deep hover:bg-wa-bubble/40">{{ __('Send reminder') }}</button>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Mark as paid') }}</button>
                        <div class="border-t border-paper-200 my-1"></div>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-accent-coral hover:bg-accent-coral/10">{{ __('Void') }}</button>
                    </div>
                </div>
            </td>
        </tr>

        <tr class="hover:bg-paper-50/60 bg-accent-coral/5">
            <td class="px-3 py-3"><input type="checkbox" class="rounded border-paper-300"></td>
            <td class="px-3 py-3 font-mono text-[11px]">{{ __('INV-2026-03791') }}</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-03-04</td>
            <td class="px-3 py-3 font-mono text-[11px] text-accent-coral">2026-03-19 · 39d late</td>
            <td class="px-3 py-3">
                <div class="font-semibold leading-tight">{{ __('PixelPlay Studio') }}</div>
                <div class="text-[10.5px] text-ink-500 font-mono">{{ __('Manish G.') }}</div>
            </td>
            <td class="px-3 py-3">
                <div class="text-[12px]">{{ __('Pro · monthly') }}</div>
                <div class="text-[10.5px] text-ink-500">3 reminders sent</div>
            </td>
            <td class="px-3 py-3 text-right font-mono text-accent-coral">$899.00</td>
            <td class="px-3 py-3 text-center"><span
                    class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-accent-coral/10 text-accent-coral text-[10.5px] font-mono"><span
                        class="w-1.5 h-1.5 rounded-full bg-accent-coral"></span>overdue</span></td>
            <td class="px-3 py-3 text-center"><a href="{{ url('/admin/invoices/1') }}"
                    class="inline-flex w-7 h-7 rounded-full border border-paper-200 hover:border-wa-deep hover:bg-wa-bubble text-wa-deep grid place-items-center"
                    title="{{ __('View invoice') }}"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5" fill="none"
                        stroke="currentColor" stroke-width="1.6">
                        <path d="M8 2v8m0 0L5 7m3 3 3-3M3 13h10" />
                    </svg></a></td>
            <td class="px-3 py-3 text-center">
                <div class="relative inline-block"><button type="button"
                        class="w-8 h-8 rounded-full hover:bg-paper-50 grid place-items-center mx-auto"
                        onclick="toggleInvMenu(event,this)"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5 text-ink-600"
                            fill="currentColor">
                            <circle cx="3" cy="8" r="1.2" />
                            <circle cx="8" cy="8" r="1.2" />
                            <circle cx="13" cy="8" r="1.2" />
                        </svg></button>
                    <div
                        class="inv-action-menu hidden absolute right-0 top-full mt-1 z-50 w-[180px] bg-paper-0 border border-paper-200 rounded-xl shadow-soft py-1 text-left">
                        <a href="{{ url('/admin/invoices/1') }}"
                            class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('View') }}</a>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-wa-deep hover:bg-wa-bubble/40">{{ __('Send dunning email') }}</button>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Charge again') }}</button>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Mark as paid') }}</button>
                        <div class="border-t border-paper-200 my-1"></div>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-accent-coral hover:bg-accent-coral/10">{{ __('Suspend workspace') }}</button>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-accent-coral hover:bg-accent-coral/10">{{ __('Write off') }}</button>
                    </div>
                </div>
            </td>
        </tr>

        <tr class="hover:bg-paper-50/60">
            <td class="px-3 py-3"><input type="checkbox" class="rounded border-paper-300"></td>
            <td class="px-3 py-3 font-mono text-[11px]">{{ __('INV-2026-03790') }}</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-04-04</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-04-04</td>
            <td class="px-3 py-3">
                <div class="font-semibold leading-tight">{{ __('Northstar Clinic') }}</div>
                <div class="text-[10.5px] text-ink-500 font-mono">{{ __('Anya M.') }}</div>
            </td>
            <td class="px-3 py-3">
                <div class="text-[12px]">{{ __('Enterprise · annual') }}</div>
                <div class="text-[10.5px] text-ink-500">2026 fiscal year</div>
            </td>
            <td class="px-3 py-3 text-right font-mono text-wa-deep">$38,400.00</td>
            <td class="px-3 py-3 text-center"><span
                    class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-wa-mint text-wa-deep text-[10.5px] font-mono"><span
                        class="w-1.5 h-1.5 rounded-full bg-wa-green"></span>paid</span></td>
            <td class="px-3 py-3 text-center"><a href="{{ url('/admin/invoices/1') }}"
                    class="inline-flex w-7 h-7 rounded-full border border-paper-200 hover:border-wa-deep hover:bg-wa-bubble text-wa-deep grid place-items-center"
                    title="{{ __('View invoice') }}"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5" fill="none"
                        stroke="currentColor" stroke-width="1.6">
                        <path d="M8 2v8m0 0L5 7m3 3 3-3M3 13h10" />
                    </svg></a></td>
            <td class="px-3 py-3 text-center">
                <div class="relative inline-block"><button type="button"
                        class="w-8 h-8 rounded-full hover:bg-paper-50 grid place-items-center mx-auto"
                        onclick="toggleInvMenu(event,this)"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5 text-ink-600"
                            fill="currentColor">
                            <circle cx="3" cy="8" r="1.2" />
                            <circle cx="8" cy="8" r="1.2" />
                            <circle cx="13" cy="8" r="1.2" />
                        </svg></button>
                    <div
                        class="inv-action-menu hidden absolute right-0 top-full mt-1 z-50 w-[180px] bg-paper-0 border border-paper-200 rounded-xl shadow-soft py-1 text-left">
                        <a href="{{ url('/admin/invoices/1') }}"
                            class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('View') }}</a>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Email to owner') }}</button>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Regenerate PDF') }}</button>
                    </div>
                </div>
            </td>
        </tr>

        <tr class="hover:bg-paper-50/60">
            <td class="px-3 py-3"><input type="checkbox" class="rounded border-paper-300"></td>
            <td class="px-3 py-3 font-mono text-[11px]">{{ __('INV-2026-03789') }}</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-04-04</td>
            <td class="px-3 py-3 font-mono text-[11px]">2026-04-04</td>
            <td class="px-3 py-3">
                <div class="font-semibold leading-tight">{{ __('DesignHub') }}</div>
                <div class="text-[10.5px] text-ink-500 font-mono">{{ __('Karthik N.') }}</div>
            </td>
            <td class="px-3 py-3">
                <div class="text-[12px]">{{ __('Pro · monthly') }}</div>
                <div class="text-[10.5px] text-ink-500">{{ __('refunded') }}</div>
            </td>
            <td class="px-3 py-3 text-right font-mono text-accent-coral">-$899.00</td>
            <td class="px-3 py-3 text-center"><span
                    class="inline-flex items-center gap-1 px-2 py-0.5 rounded-full bg-paper-100 text-ink-700 text-[10.5px] font-mono">{{ __('refunded') }}</span>
            </td>
            <td class="px-3 py-3 text-center"><a href="{{ url('/admin/invoices/1') }}"
                    class="inline-flex w-7 h-7 rounded-full border border-paper-200 hover:border-wa-deep hover:bg-wa-bubble text-wa-deep grid place-items-center"
                    title="{{ __('View invoice') }}"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5" fill="none"
                        stroke="currentColor" stroke-width="1.6">
                        <path d="M8 2v8m0 0L5 7m3 3 3-3M3 13h10" />
                    </svg></a></td>
            <td class="px-3 py-3 text-center">
                <div class="relative inline-block"><button type="button"
                        class="w-8 h-8 rounded-full hover:bg-paper-50 grid place-items-center mx-auto"
                        onclick="toggleInvMenu(event,this)"><svg viewBox="0 0 16 16" class="w-3.5 h-3.5 text-ink-600"
                            fill="currentColor">
                            <circle cx="3" cy="8" r="1.2" />
                            <circle cx="8" cy="8" r="1.2" />
                            <circle cx="13" cy="8" r="1.2" />
                        </svg></button>
                    <div
                        class="inv-action-menu hidden absolute right-0 top-full mt-1 z-50 w-[180px] bg-paper-0 border border-paper-200 rounded-xl shadow-soft py-1 text-left">
                        <a href="{{ url('/admin/invoices/1') }}"
                            class="flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('View credit note') }}</a>
                        <button
                            class="w-full text-left flex items-center gap-2.5 px-3 py-2 text-[12.5px] text-ink-700 hover:bg-paper-50">{{ __('Email to owner') }}</button>
                    </div>
                </div>
            </td>
        </tr>
        @endif
        </tbody>
        </table>
        </div>
        <div
            class="px-4 py-3 border-t border-paper-200 bg-paper-50/40 rounded-b-2xl flex flex-wrap gap-2 items-center justify-between">
            <div class="text-[11px] font-mono text-ink-500">Showing
                {{ $invoices->firstItem() ?? 0 }}–{{ $invoices->lastItem() ?? 0 }} of
                {{ number_format($invoices->total()) }} {{ __('invoices') }}</div>
            <div>{{ $invoices->onEachSide(1)->links() }}</div>
        </div>
        </div>
    </main>

</x-layouts.admin>
